name: Build and test

on:
  push:
  pull_request:

jobs:
  ubuntu-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: eessi/github-action-eessi@v3
      with:
        eessi_stack_version: '2025.06'
    - name: Build our application
      run: |
        module load CMake/4.0.3-GCCcore-14.3.0  
        module load HDF5/1.14.6-gompi-2025b  
        module load buildenv/default-foss-2025b  
        mkdir build
        cd build
        cmake ..  
        make -j  
        ctest --output-on-failure --verbose
      shell: bash
