name: Ubuntu Minimal EESSI Easyconfig Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: eessi/github-action-eessi@v3
    - name: Test Easyconfig with EESSI
      run: |
        module load EESSI-extend
        eb easybuild/build.eb --software-commit=$GITHUB_SHA
      shell: bash
